apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crowdvision

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - mediamtx.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml