apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: backend-gpu.yaml

images:
  - name: registry.example.com/crowdvision/crowd-backend
    newName: registry.example.com/crowdvision/crowd-backend
    newTag: client-1.0.0
  - name: registry.example.com/crowdvision/crowd-frontend
    newName: registry.example.com/crowdvision/crowd-frontend
    newTag: client-1.0.0