apiVersion: v1
kind: Service
metadata:
  name: crowdvision-backend
  labels:
    app.kubernetes.io/name: crowdvision-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crowdvision-backend
  ports:
    - name: http
      port: 80
      targetPort: http