apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crowdvision
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - crowdvision.example.com
      secretName: crowdvision-tls
  rules:
    - host: crowdvision.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crowdvision-backend
                port:
                  name: http