apiVersion: v1
kind: Service
metadata:
  name: mediamtx
  labels:
    app.kubernetes.io/name: mediamtx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mediamtx
  ports:
    - name: rtsp
      port: 8554
      targetPort: rtsp
    - name: hls
      port: 8888
      targetPort: hls
    - name: webrtc
      port: 8889
      targetPort: webrtc