sonar.projectKey=crowd-backend
sonar.projectName=crowd-backend
sonar.projectVersion=1.0
sonar.sources=api,config,db,models,modules,services,util,utils,scripts
sonar.python.version=3.12
sonar.exclusions=**/tests/**,**/.venv/**,**/venv/**,**/node_modules/**,**/migrations/**
sonar.sourceEncoding=UTF-8
