apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.example.com/crowdvision/crowd-backend
    newName: crowdvision-backend
    newTag: local
  - name: registry.example.com/crowdvision/crowd-frontend
    newName: crowdvision-frontend
    newTag: local

patches:
  - target:
      kind: Deployment
      name: crowdvision-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: crowdvision-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never